services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: workout_assistant_app
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${POSTGRES_DB}
            - DB_USERNAME=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - APP_DEBUG=false
        depends_on:
            db:
                condition: service_healthy
        networks:
            - workout-network
    web:
        image: nginx:alpine
        container_name: workout_assistant_web
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - workout-network
    db:
        image: postgres:16-alpine
        container_name: workout_assistant_db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - workout-network
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: workout_assistant_pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8081:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db
        networks:
            - workout-network

volumes:
    db_data:
    pgadmin_data:

networks:
    workout-network:
        driver: bridge
